[package]
name = "wools"
version = "0.1.0"
edition = "2021"
description = "Tools for the Wordle game."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
